### ISSUE TITLE
Add C docs

### ISSUE THREAD

**Issue by dimonomid** [mongoose-os-libs/onewire-rmt#2]
Hi, thanks for implementing that library!

Could you please add C documentation (by analogy with e.g. [arduino-bme280](https://github.com/mongoose-os-libs/arduino-adafruit-bme280/blob/master/include/mgos_arduino_bme280.h)), so that we have docs nicely rendered at https://mongoose-os.com/docs/api/mgos_onewire_rmt.h.html ?

Thanks!

**Comment by nliviu** [comment]
Done.
